title: Seb Larsen blog
email: your-email@example.com
description: "Musings of a Mechanical Engineer"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://seblars.github.io/"
twitter_username: sebastianlarsen
github_username:  seblars

# # Build settings
# theme: minima
# plugins:
#   - jekyll-feed

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
